#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("x", 16, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("L", 16, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("a3_r0", 16, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("a2_r0", 16, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("a1_r0", 16, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("a0_r0", 16, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("a3_r1", 16, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("a2_r1", 16, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("a1_r1", 16, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("a0_r1", 16, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("a3_r2", 16, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("a2_r2", 16, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("a1_r2", 16, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("a0_r2", 16, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("ap_return", 16, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "camta";
