// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="camta_camta,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.979500,HLS_SYN_LAT=7,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=589,HLS_SYN_LUT=2162,HLS_VERSION=2023_2}" *)

module camta (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        L,
        a3_r0,
        a2_r0,
        a1_r0,
        a0_r0,
        a3_r1,
        a2_r1,
        a1_r1,
        a0_r1,
        a3_r2,
        a2_r2,
        a1_r2,
        a0_r2,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] x;
input  [15:0] L;
input  [15:0] a3_r0;
input  [15:0] a2_r0;
input  [15:0] a1_r0;
input  [15:0] a0_r0;
input  [15:0] a3_r1;
input  [15:0] a2_r1;
input  [15:0] a1_r1;
input  [15:0] a0_r1;
input  [15:0] a3_r2;
input  [15:0] a2_r2;
input  [15:0] a1_r2;
input  [15:0] a0_r2;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [15:0] x_read_reg_239;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] a3_fu_207_p3;
reg   [15:0] a3_reg_244;
wire   [15:0] a2_fu_215_p3;
reg   [15:0] a2_reg_249;
wire   [15:0] a1_fu_223_p3;
reg   [15:0] a1_reg_254;
wire   [15:0] a0_fu_231_p3;
reg   [15:0] a0_reg_259;
wire   [15:0] grp_horner_core_fu_140_ap_return;
reg    grp_horner_core_fu_140_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp36;
wire    ap_block_pp0_stage0;
wire  signed [15:0] sext_ln17_fu_149_p0;
wire  signed [16:0] sext_ln17_fu_149_p1;
wire  signed [15:0] sext_ln17_1_fu_159_p0;
wire  signed [16:0] sext_ln17_1_fu_159_p1;
wire   [16:0] sub_ln17_fu_153_p2;
wire  signed [15:0] icmp_ln20_fu_169_p0;
wire  signed [15:0] icmp_ln20_fu_169_p1;
wire   [0:0] icmp_ln20_fu_169_p2;
wire   [0:0] icmp_ln17_fu_163_p2;
wire   [15:0] select_ln20_fu_175_p3;
wire   [15:0] select_ln20_1_fu_183_p3;
wire   [15:0] select_ln20_2_fu_191_p3;
wire   [15:0] select_ln20_3_fu_199_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to6;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
end

camta_horner_core grp_horner_core_fu_140(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x_val(x_read_reg_239),
    .a3_val(a3_reg_244),
    .a2_val(a2_reg_249),
    .a1_val(a1_reg_254),
    .a0_val(a0_reg_259),
    .ap_return(grp_horner_core_fu_140_ap_return),
    .ap_ce(grp_horner_core_fu_140_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a0_reg_259 <= a0_fu_231_p3;
        a1_reg_254 <= a1_fu_223_p3;
        a2_reg_249 <= a2_fu_215_p3;
        a3_reg_244 <= a3_fu_207_p3;
        x_read_reg_239 <= x;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to6 = 1'b1;
    end else begin
        ap_idle_pp0_0to6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp36) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_horner_core_fu_140_ap_ce = 1'b1;
    end else begin
        grp_horner_core_fu_140_ap_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a0_fu_231_p3 = ((icmp_ln17_fu_163_p2[0:0] == 1'b1) ? a0_r0 : select_ln20_3_fu_199_p3);

assign a1_fu_223_p3 = ((icmp_ln17_fu_163_p2[0:0] == 1'b1) ? a1_r0 : select_ln20_2_fu_191_p3);

assign a2_fu_215_p3 = ((icmp_ln17_fu_163_p2[0:0] == 1'b1) ? a2_r0 : select_ln20_1_fu_183_p3);

assign a3_fu_207_p3 = ((icmp_ln17_fu_163_p2[0:0] == 1'b1) ? a3_r0 : select_ln20_fu_175_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp36 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = grp_horner_core_fu_140_ap_return;

assign icmp_ln17_fu_163_p2 = (($signed(sext_ln17_1_fu_159_p1) < $signed(sub_ln17_fu_153_p2)) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_169_p0 = x;

assign icmp_ln20_fu_169_p1 = L;

assign icmp_ln20_fu_169_p2 = (($signed(icmp_ln20_fu_169_p0) > $signed(icmp_ln20_fu_169_p1)) ? 1'b1 : 1'b0);

assign select_ln20_1_fu_183_p3 = ((icmp_ln20_fu_169_p2[0:0] == 1'b1) ? a2_r2 : a2_r1);

assign select_ln20_2_fu_191_p3 = ((icmp_ln20_fu_169_p2[0:0] == 1'b1) ? a1_r2 : a1_r1);

assign select_ln20_3_fu_199_p3 = ((icmp_ln20_fu_169_p2[0:0] == 1'b1) ? a0_r2 : a0_r1);

assign select_ln20_fu_175_p3 = ((icmp_ln20_fu_169_p2[0:0] == 1'b1) ? a3_r2 : a3_r1);

assign sext_ln17_1_fu_159_p0 = x;

assign sext_ln17_1_fu_159_p1 = sext_ln17_1_fu_159_p0;

assign sext_ln17_fu_149_p0 = L;

assign sext_ln17_fu_149_p1 = sext_ln17_fu_149_p0;

assign sub_ln17_fu_153_p2 = ($signed(17'd0) - $signed(sext_ln17_fu_149_p1));

endmodule //camta
