-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity camta is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (15 downto 0);
    L : IN STD_LOGIC_VECTOR (15 downto 0);
    a3_r0 : IN STD_LOGIC_VECTOR (15 downto 0);
    a2_r0 : IN STD_LOGIC_VECTOR (15 downto 0);
    a1_r0 : IN STD_LOGIC_VECTOR (15 downto 0);
    a0_r0 : IN STD_LOGIC_VECTOR (15 downto 0);
    a3_r1 : IN STD_LOGIC_VECTOR (15 downto 0);
    a2_r1 : IN STD_LOGIC_VECTOR (15 downto 0);
    a1_r1 : IN STD_LOGIC_VECTOR (15 downto 0);
    a0_r1 : IN STD_LOGIC_VECTOR (15 downto 0);
    a3_r2 : IN STD_LOGIC_VECTOR (15 downto 0);
    a2_r2 : IN STD_LOGIC_VECTOR (15 downto 0);
    a1_r2 : IN STD_LOGIC_VECTOR (15 downto 0);
    a0_r2 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of camta is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "camta_camta,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.979500,HLS_SYN_LAT=7,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=589,HLS_SYN_LUT=2162,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal x_read_reg_239 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal a3_fu_207_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal a3_reg_244 : STD_LOGIC_VECTOR (15 downto 0);
    signal a2_fu_215_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal a2_reg_249 : STD_LOGIC_VECTOR (15 downto 0);
    signal a1_fu_223_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal a1_reg_254 : STD_LOGIC_VECTOR (15 downto 0);
    signal a0_fu_231_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal a0_reg_259 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_horner_core_fu_140_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_horner_core_fu_140_ap_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_ignoreCallOp36 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln17_fu_149_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln17_fu_149_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln17_1_fu_159_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln17_1_fu_159_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln17_fu_153_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln20_fu_169_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln20_fu_169_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln20_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_fu_163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln20_fu_175_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln20_1_fu_183_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln20_2_fu_191_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln20_3_fu_199_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to6 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component camta_horner_core IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x_val : IN STD_LOGIC_VECTOR (15 downto 0);
        a3_val : IN STD_LOGIC_VECTOR (15 downto 0);
        a2_val : IN STD_LOGIC_VECTOR (15 downto 0);
        a1_val : IN STD_LOGIC_VECTOR (15 downto 0);
        a0_val : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_horner_core_fu_140 : component camta_horner_core
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_val => x_read_reg_239,
        a3_val => a3_reg_244,
        a2_val => a2_reg_249,
        a1_val => a1_reg_254,
        a0_val => a0_reg_259,
        ap_return => grp_horner_core_fu_140_ap_return,
        ap_ce => grp_horner_core_fu_140_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a0_reg_259 <= a0_fu_231_p3;
                a1_reg_254 <= a1_fu_223_p3;
                a2_reg_249 <= a2_fu_215_p3;
                a3_reg_244 <= a3_fu_207_p3;
                x_read_reg_239 <= x;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a0_fu_231_p3 <= 
        a0_r0 when (icmp_ln17_fu_163_p2(0) = '1') else 
        select_ln20_3_fu_199_p3;
    a1_fu_223_p3 <= 
        a1_r0 when (icmp_ln17_fu_163_p2(0) = '1') else 
        select_ln20_2_fu_191_p3;
    a2_fu_215_p3 <= 
        a2_r0 when (icmp_ln17_fu_163_p2(0) = '1') else 
        select_ln20_1_fu_183_p3;
    a3_fu_207_p3 <= 
        a3_r0 when (icmp_ln17_fu_163_p2(0) = '1') else 
        select_ln20_fu_175_p3;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to6_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to6 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to6)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to6 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= grp_horner_core_fu_140_ap_return;

    grp_horner_core_fu_140_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp36)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp36) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_horner_core_fu_140_ap_ce <= ap_const_logic_1;
        else 
            grp_horner_core_fu_140_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln17_fu_163_p2 <= "1" when (signed(sext_ln17_1_fu_159_p1) < signed(sub_ln17_fu_153_p2)) else "0";
    icmp_ln20_fu_169_p0 <= x;
    icmp_ln20_fu_169_p1 <= L;
    icmp_ln20_fu_169_p2 <= "1" when (signed(icmp_ln20_fu_169_p0) > signed(icmp_ln20_fu_169_p1)) else "0";
    select_ln20_1_fu_183_p3 <= 
        a2_r2 when (icmp_ln20_fu_169_p2(0) = '1') else 
        a2_r1;
    select_ln20_2_fu_191_p3 <= 
        a1_r2 when (icmp_ln20_fu_169_p2(0) = '1') else 
        a1_r1;
    select_ln20_3_fu_199_p3 <= 
        a0_r2 when (icmp_ln20_fu_169_p2(0) = '1') else 
        a0_r1;
    select_ln20_fu_175_p3 <= 
        a3_r2 when (icmp_ln20_fu_169_p2(0) = '1') else 
        a3_r1;
    sext_ln17_1_fu_159_p0 <= x;
        sext_ln17_1_fu_159_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln17_1_fu_159_p0),17));

    sext_ln17_fu_149_p0 <= L;
        sext_ln17_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln17_fu_149_p0),17));

    sub_ln17_fu_153_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln17_fu_149_p1));
end behav;
