-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity camta_horner_core is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x_val : IN STD_LOGIC_VECTOR (15 downto 0);
    a3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    a2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    a1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    a0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of camta_horner_core is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";

attribute shreg_extract : string;
    signal a0_val_read_reg_208 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal a0_val_read_reg_208_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a0_val_read_reg_208_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a0_val_read_reg_208_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a0_val_read_reg_208_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a1_val_read_reg_213 : STD_LOGIC_VECTOR (15 downto 0);
    signal a1_val_read_reg_213_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a1_val_read_reg_213_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a2_val_read_reg_218 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_val_read_reg_223 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_val_read_reg_223_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_reg_228 : STD_LOGIC_VECTOR (23 downto 0);
    signal acc_1_fu_125_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal acc_1_reg_233 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln14_1_fu_130_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln14_1_reg_238 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln14_1_reg_238_pp0_iter3_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_1_reg_243 : STD_LOGIC_VECTOR (23 downto 0);
    signal acc_2_fu_163_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal acc_2_reg_248 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_2_reg_253 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal acc_fu_82_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal mul_ln14_fu_98_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal shl_ln_fu_114_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln15_fu_121_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln16_fu_136_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal shl_ln1_fu_152_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln17_fu_159_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln18_fu_171_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln18_fu_171_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal shl_ln2_fu_186_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal acc_3_fu_193_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_val_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a3_val_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a2_val_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a1_val_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal a0_val_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component camta_mul_20s_16s_36_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (19 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component camta_mul_24s_16s_40_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;



begin
    mul_20s_16s_36_1_0_U1 : component camta_mul_20s_16s_36_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 20,
        din1_WIDTH => 16,
        dout_WIDTH => 36)
    port map (
        din0 => acc_fu_82_p3,
        din1 => x_val_int_reg,
        dout => mul_ln14_fu_98_p2);

    mul_24s_16s_40_1_0_U2 : component camta_mul_24s_16s_40_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 16,
        dout_WIDTH => 40)
    port map (
        din0 => acc_1_reg_233,
        din1 => x_val_read_reg_223_pp0_iter1_reg,
        dout => mul_ln16_fu_136_p2);

    mul_24s_16s_40_1_0_U3 : component camta_mul_24s_16s_40_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 16,
        dout_WIDTH => 40)
    port map (
        din0 => acc_2_reg_248,
        din1 => mul_ln18_fu_171_p1,
        dout => mul_ln18_fu_171_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                a0_val_int_reg <= a0_val;
                a1_val_int_reg <= a1_val;
                a2_val_int_reg <= a2_val;
                a3_val_int_reg <= a3_val;
                x_val_int_reg <= x_val;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                a0_val_read_reg_208 <= a0_val_int_reg;
                a0_val_read_reg_208_pp0_iter1_reg <= a0_val_read_reg_208;
                a0_val_read_reg_208_pp0_iter2_reg <= a0_val_read_reg_208_pp0_iter1_reg;
                a0_val_read_reg_208_pp0_iter3_reg <= a0_val_read_reg_208_pp0_iter2_reg;
                a0_val_read_reg_208_pp0_iter4_reg <= a0_val_read_reg_208_pp0_iter3_reg;
                a1_val_read_reg_213 <= a1_val_int_reg;
                a1_val_read_reg_213_pp0_iter1_reg <= a1_val_read_reg_213;
                a1_val_read_reg_213_pp0_iter2_reg <= a1_val_read_reg_213_pp0_iter1_reg;
                a2_val_read_reg_218 <= a2_val_int_reg;
                acc_1_reg_233 <= acc_1_fu_125_p2;
                acc_2_reg_248 <= acc_2_fu_163_p2;
                mul_1_reg_243 <= mul_ln16_fu_136_p2(33 downto 10);
                mul_2_reg_253 <= mul_ln18_fu_171_p2(29 downto 10);
                mul_reg_228 <= mul_ln14_fu_98_p2(33 downto 10);
                sext_ln14_1_reg_238 <= sext_ln14_1_fu_130_p1;
                sext_ln14_1_reg_238_pp0_iter3_reg <= sext_ln14_1_reg_238;
                x_val_read_reg_223 <= x_val_int_reg;
                x_val_read_reg_223_pp0_iter1_reg <= x_val_read_reg_223;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= acc_3_fu_193_p2(19 downto 4);
            end if;
        end if;
    end process;
    acc_1_fu_125_p2 <= std_logic_vector(unsigned(mul_reg_228) + unsigned(sext_ln15_fu_121_p1));
    acc_2_fu_163_p2 <= std_logic_vector(unsigned(mul_1_reg_243) + unsigned(sext_ln17_fu_159_p1));
    acc_3_fu_193_p2 <= std_logic_vector(unsigned(mul_2_reg_253) + unsigned(shl_ln2_fu_186_p3));
    acc_fu_82_p3 <= (a3_val_int_reg & ap_const_lv4_0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(acc_3_fu_193_p2, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= acc_3_fu_193_p2(19 downto 4);
        else 
            ap_return <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    mul_ln18_fu_171_p1 <= sext_ln14_1_reg_238_pp0_iter3_reg(16 - 1 downto 0);
        sext_ln14_1_fu_130_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_val_read_reg_223_pp0_iter1_reg),40));

        sext_ln15_fu_121_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_114_p3),24));

        sext_ln17_fu_159_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1_fu_152_p3),24));

    shl_ln1_fu_152_p3 <= (a1_val_read_reg_213_pp0_iter2_reg & ap_const_lv4_0);
    shl_ln2_fu_186_p3 <= (a0_val_read_reg_208_pp0_iter4_reg & ap_const_lv4_0);
    shl_ln_fu_114_p3 <= (a2_val_read_reg_218 & ap_const_lv4_0);
end behav;
