// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module camta_horner_core (
        ap_clk,
        ap_rst,
        x_val,
        a3_val,
        a2_val,
        a1_val,
        a0_val,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] x_val;
input  [15:0] a3_val;
input  [15:0] a2_val;
input  [15:0] a1_val;
input  [15:0] a0_val;
output  [15:0] ap_return;
input   ap_ce;

reg[15:0] ap_return;

reg   [15:0] a0_val_read_reg_208;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] a0_val_read_reg_208_pp0_iter1_reg;
reg   [15:0] a0_val_read_reg_208_pp0_iter2_reg;
reg   [15:0] a0_val_read_reg_208_pp0_iter3_reg;
reg   [15:0] a0_val_read_reg_208_pp0_iter4_reg;
reg   [15:0] a1_val_read_reg_213;
reg   [15:0] a1_val_read_reg_213_pp0_iter1_reg;
reg   [15:0] a1_val_read_reg_213_pp0_iter2_reg;
reg   [15:0] a2_val_read_reg_218;
reg  signed [15:0] x_val_read_reg_223;
reg  signed [15:0] x_val_read_reg_223_pp0_iter1_reg;
reg   [23:0] mul_reg_228;
wire   [23:0] acc_1_fu_125_p2;
reg  signed [23:0] acc_1_reg_233;
wire  signed [39:0] sext_ln14_1_fu_130_p1;
reg  signed [39:0] sext_ln14_1_reg_238;
reg  signed [39:0] sext_ln14_1_reg_238_pp0_iter3_reg;
reg   [23:0] mul_1_reg_243;
wire   [23:0] acc_2_fu_163_p2;
reg  signed [23:0] acc_2_reg_248;
reg   [19:0] mul_2_reg_253;
wire    ap_block_pp0_stage0;
wire  signed [19:0] acc_fu_82_p3;
wire   [35:0] mul_ln14_fu_98_p2;
wire   [19:0] shl_ln_fu_114_p3;
wire  signed [23:0] sext_ln15_fu_121_p1;
wire   [39:0] mul_ln16_fu_136_p2;
wire   [19:0] shl_ln1_fu_152_p3;
wire  signed [23:0] sext_ln17_fu_159_p1;
wire  signed [15:0] mul_ln18_fu_171_p1;
wire   [39:0] mul_ln18_fu_171_p2;
wire   [19:0] shl_ln2_fu_186_p3;
wire   [19:0] acc_3_fu_193_p2;
reg    ap_ce_reg;
reg  signed [15:0] x_val_int_reg;
reg   [15:0] a3_val_int_reg;
reg   [15:0] a2_val_int_reg;
reg   [15:0] a1_val_int_reg;
reg   [15:0] a0_val_int_reg;
reg   [15:0] ap_return_int_reg;

camta_mul_20s_16s_36_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 36 ))
mul_20s_16s_36_1_0_U1(
    .din0(acc_fu_82_p3),
    .din1(x_val_int_reg),
    .dout(mul_ln14_fu_98_p2)
);

camta_mul_24s_16s_40_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 40 ))
mul_24s_16s_40_1_0_U2(
    .din0(acc_1_reg_233),
    .din1(x_val_read_reg_223_pp0_iter1_reg),
    .dout(mul_ln16_fu_136_p2)
);

camta_mul_24s_16s_40_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 40 ))
mul_24s_16s_40_1_0_U3(
    .din0(acc_2_reg_248),
    .din1(mul_ln18_fu_171_p1),
    .dout(mul_ln18_fu_171_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        a0_val_int_reg <= a0_val;
        a1_val_int_reg <= a1_val;
        a2_val_int_reg <= a2_val;
        a3_val_int_reg <= a3_val;
        x_val_int_reg <= x_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        a0_val_read_reg_208 <= a0_val_int_reg;
        a0_val_read_reg_208_pp0_iter1_reg <= a0_val_read_reg_208;
        a0_val_read_reg_208_pp0_iter2_reg <= a0_val_read_reg_208_pp0_iter1_reg;
        a0_val_read_reg_208_pp0_iter3_reg <= a0_val_read_reg_208_pp0_iter2_reg;
        a0_val_read_reg_208_pp0_iter4_reg <= a0_val_read_reg_208_pp0_iter3_reg;
        a1_val_read_reg_213 <= a1_val_int_reg;
        a1_val_read_reg_213_pp0_iter1_reg <= a1_val_read_reg_213;
        a1_val_read_reg_213_pp0_iter2_reg <= a1_val_read_reg_213_pp0_iter1_reg;
        a2_val_read_reg_218 <= a2_val_int_reg;
        acc_1_reg_233 <= acc_1_fu_125_p2;
        acc_2_reg_248 <= acc_2_fu_163_p2;
        mul_1_reg_243 <= {{mul_ln16_fu_136_p2[33:10]}};
        mul_2_reg_253 <= {{mul_ln18_fu_171_p2[29:10]}};
        mul_reg_228 <= {{mul_ln14_fu_98_p2[33:10]}};
        sext_ln14_1_reg_238 <= sext_ln14_1_fu_130_p1;
        sext_ln14_1_reg_238_pp0_iter3_reg <= sext_ln14_1_reg_238;
        x_val_read_reg_223 <= x_val_int_reg;
        x_val_read_reg_223_pp0_iter1_reg <= x_val_read_reg_223;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= {{acc_3_fu_193_p2[19:4]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = {{acc_3_fu_193_p2[19:4]}};
    end else begin
        ap_return = 'bx;
    end
end

assign acc_1_fu_125_p2 = ($signed(mul_reg_228) + $signed(sext_ln15_fu_121_p1));

assign acc_2_fu_163_p2 = ($signed(mul_1_reg_243) + $signed(sext_ln17_fu_159_p1));

assign acc_3_fu_193_p2 = (mul_2_reg_253 + shl_ln2_fu_186_p3);

assign acc_fu_82_p3 = {{a3_val_int_reg}, {4'd0}};

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign mul_ln18_fu_171_p1 = sext_ln14_1_reg_238_pp0_iter3_reg;

assign sext_ln14_1_fu_130_p1 = x_val_read_reg_223_pp0_iter1_reg;

assign sext_ln15_fu_121_p1 = $signed(shl_ln_fu_114_p3);

assign sext_ln17_fu_159_p1 = $signed(shl_ln1_fu_152_p3);

assign shl_ln1_fu_152_p3 = {{a1_val_read_reg_213_pp0_iter2_reg}, {4'd0}};

assign shl_ln2_fu_186_p3 = {{a0_val_read_reg_208_pp0_iter4_reg}, {4'd0}};

assign shl_ln_fu_114_p3 = {{a2_val_read_reg_218}, {4'd0}};

endmodule //camta_horner_core
